AWSTemplateFormatVersion: "2010-09-09"
Description: "Airflow Code Repository CloudFormation Stack"

Parameters:
  CodeCommitRepositoryName:
    Description: CodeCommit Repository name
    Type: String

Resources:
# ###########################################
# # CodeCommit Repository
# ###########################################
  CodeCommitPythonRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref CodeCommitRepositoryName
