AWSTemplateFormatVersion: "2010-09-09"
Description: "Airflow Data CloudFormation Stack"

Parameters:
  S3BucketName:
    Description: S3 Bucket name
    Type: String

Resources:
###########################################
# S3 Bucket Airflow
###########################################
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
